### ISSUE TITLE
[BUG] Reading 2D images requires depth_pixel_spacing

### ISSUE THREAD

**Issue by laurencejackson** [Project-MONAI/monai-deploy-app-sdk#133]
**Describe the bug**
When reading 2D dicom images using the `InMemImageReader._get_meta_dict()` method the meta_dict["spacing"] variable requires that the image metadata has a value for depth_pixel_spacing. The code that assigns this value is currently skipped by the SOP instance count check in DICOMSeriesToVolumeOperator.prepare_series. 

The exception occurs when running line 62:
![image](https://user-images.githubusercontent.com/33687657/133605830-b3b27067-8ffd-4631-9287-402a3f465355.png)

**Steps/Code to reproduce bug**
Attempting to use the pytorch dataloader with any series composed of a single SOP instance should reproduce this bug.

**Expected behavior**
I would expect the depth_pixel_spacing to not be required for a 2D image series. It would be fantastic if we could use a single generic series to volume operator that is compatible with ND series

**Environment details (please complete the following information)**

- OS/Platform: Mac OS 11.2
- Python Version: 3.8
- Method of MONAI Deploy App SDK install: [pip, conda, Docker, or from source] built from source commit 8e344fa4e6871353f0fc929846463e75e85d234b
- SDK Version: 8e344fa4e6871353f0fc929846463e75e85d234b

**Additional context**
N/A

**Comment by MMelQin** [comment]
The DICOMSeriesToVolumeOperator needs to set the depth_pixel_spacing even for 2D image, with a value of 1.0. This is consistent with what ITK loading DICOM series.
The change will be made as part of PR #238

**Comment by MMelQin** [comment]
Fixed in #238
