### ISSUE TITLE
[BUG] Output shape of SpleenSegOperator does not match input shape

### ISSUE THREAD

**Issue by AndreasHeumann** [Project-MONAI/monai-deploy-app-sdk#159]
**Describe the bug**

When executing the 03_segmentation_app.ipynb notebook the segmentation data output by the SpleenSegOperator is transposed compared to the input. The spleenSegOperator prints 'Output Seg image numpy array shaped: (515, 440, 440)'. But the input data has the shape '(440, 440, 515)'.

**Steps/Code to reproduce bug**

Start jupyter lab, load 03_segmentation_app.ipynb, run up to 'Executing app locally'. Watch the output of the SpleenSegOperator, it prints 'Output Seg image numpy array shaped: (515, 440, 440)'. Inspect the shape of the input data, it's different.

**Expected behavior**

The output data of the of the SpleenSegOperator should have the same shape as the input data.

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu 20.04
- Python Version: 3.8
- Method of MONAI Deploy App SDK install: from source
- SDK Version: 0.1.1rc2

**Additional context**

The source data consist of 515 slices of 440x440 pixels each.
The way the density array data is stored into memory is also not optimal, it is not stored contiguously in memory.

shape (440, 440, 515)
strides (1030, 453200, 2)

I'd expect these values for shape and strides:

shape (550, 440, 440)
strides (453200, 1030, 2)

Segementation data is stored contiguously but not as an array of slices

shape (515, 440, 440)
strides (1, 515, 226600)

**Comment by AndreasHeumann** [comment]
@MMelQin Thanks for the explanation. I saw you created a new issue to have consistent shape information across execution. We should be consistent which the way numpy defines the shape, starting with the 'fastest' varying axis and ending with the 'slowest'. For the case of 3D arrays that would be WHD (width-height-depth).

I'm closing this issue, like you said, it's not a bug per definition.

**Comment by MMelQin** [comment]
@AndreasHeumann Thanks. Yes, the Image class has to be tightened up quite a bit.
