### ISSUE TITLE
[BUG] ERROR: Failed to fetch MAP manifest.

### ISSUE THREAD

**Issue by jpcenteno80** [Project-MONAI/monai-deploy-app-sdk#165]
**Describe the bug**
Above error displayed when trying to run packaged app.

**Steps/Code to reproduce bug**
```
# Inside monai-deploy-app-sdk/examples/apps/
monai-deploy package ./simple_imaging_app -t simple_app:latest

# output:
Building MONAI Application Package... Done
[2021-10-08 11:04:07,763] [INFO] (app_packager) - Successfully built simple_app:latest

monai-deploy run simple_app:latest input output # where input has brain_mr_input.jpg and output is an empty directory

# output:
Checking dependencies...
--> Verifying if "docker" is installed...

--> Verifying if "simple_app:latest" is available...

Checking for MAP "simple_app:latest" locally
"simple_app:latest" found.

Reading MONAI App Package manifest...
 > export '/var/run/monai/export/' detected
fatal: Access to the path '/var/run/monai/export/config/pkg.json' is denied.
ERROR: Failed to fetch MAP manifest.
Execution Aborted
```

**Expected behavior**
App should run.

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu 18
- Python Version: 3.9.7
- Method of MONAI Deploy App SDK install: `pip install monai-deploy-app-sdk`
- SDK Version: 0.1.0

**Additional context**
This is an AWS instance where I created my own user. App was packaged under my user.

**Comment by gigony** [comment]
Thanks @jpcenteno80  for the feedback!

`monai-deploy-app-sdk` package and its dependent pip packages are copied/added by default when `monai-deploy package` command is used.

https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/41eddc4bc4a7a9e9839377622da75334d323a2b3/monai/deploy/packager/util.py#L155-L158

https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/41eddc4bc4a7a9e9839377622da75334d323a2b3/monai/deploy/packager/util.py#L165-L167

https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/20bb941d67d9e12d64d3f99dd9001d15d536ae70/monai/deploy/packager/templates.py#L47

`monai-deploy-app-sdk` is a general-purpose deploy framework on the healthcare domain (such as genomics/biochemistry workflows) so it doesn't depend on `monai` package (MONAI Core) and it needs to be manually specified if your application uses `monai` package.

We have a plan to support automatic inferring pip packages used in the application in the future.
- #170 

Could you please share the error message when `monai` library is not specified in `@md.env ` decorator?

Was your application using `monai` library?
If not, it is a bug and I have a fix for that below.

- #169 

Please let us know.

Thank you for trying out MONAI Deploy App SDK and giving us the valuable feedback!

**Comment by jpcenteno80** [comment]
Thanks for the additional information.

Back to the error when `monai` is not specified in the `@md.env` decorator:
The app I created does not use `monai` directly, it relies on the operators already implemented in `monai-deploy-app-sdk` plus an additional operator created by me. Imports for both `app.py` and my own `nrrd_converter_operator.py` are below:
```
# app.py
from monai.deploy.core import Application
from monai.deploy.operators.dicom_data_loader_operator import DICOMDataLoaderOperator
from monai.deploy.operators.dicom_series_selector_operator import DICOMSeriesSelectorOperator
from monai.deploy.operators.dicom_series_to_volume_operator import DICOMSeriesToVolumeOperator
from nrrd_converter_operator import NRRDConverterOperator
```

```
# nrrd_converter_operator.py
import hashlib, os
import numpy as np, SimpleITK as sitk

import monai.deploy.core as md
from monai.deploy.core import DataPath, ExecutionContext, Image, InputContext, IOType, Operator, OutputContext
from monai.deploy.operators.dicom_data_loader_operator import DICOMDataLoaderOperator
from monai.deploy.operators.dicom_series_to_volume_operator import DICOMSeriesToVolumeOperator
```

The error I was getting before adding `monai` to the `@md.env` decorator is the following:
```
Checking dependencies...
--> Verifying if "docker" is installed...

--> Verifying if "dicom_to_nrrd_op:latest" is available...

Checking for MAP "dicom_to_nrrd_op:latest" locally
"dicom_to_nrrd_op:latest" found.

Reading MONAI App Package manifest...
Traceback (most recent call last):
  File "/opt/monai/app/app.py", line 2, in <module>
    from monai.deploy.operators.dicom_data_loader_operator import DICOMDataLoaderOperator
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/operators/__init__.py", line 29, in <module>
    from .monai_seg_inference_operator import MonaiSegInferenceOperator
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/operators/monai_seg_inference_operator.py", line 237, in <module>
    class InMemImageReader(ImageReader):
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/utils/importutil.py", line 258, in __getattr__
    raise self._exception
  File "/home/monai/.local/lib/python3.8/site-packages/monai/deploy/utils/importutil.py", line 217, in optional_import
    pkg = __import__(module)  # top level module
monai.deploy.utils.importutil.OptionalImportError: from monai.data import ImageReader (No module named 'monai.data').

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies
```

And an additional comment regarding image sizes... I noticed in the documentation that future support for smaller base images is in the pipeline, so that is great. This small app I created is ~15 gigs, using the default nvidia pytorch image:
```
nvcr.io/nvidia/pytorch   21.07-py3                 7beec3ff8d35        2 months ago        15GB
```

I tried to build it with a smaller base image, but it throws an error:
```
monai-deploy package src/dicom_series_to_nrrd_app -t dicom_to_nrrd_op:latest -b nvcr.io/nvidia/cuda:11.4.1-base-ubuntu18.04 

# error
Building MONAI Application Package... -The command '/bin/sh -c pip install --no-cache-dir --upgrade -r /tmp/requirements.txt' returned a non-zero code: 1
```

Also noticed in the documentation that images from `nvcr.io` are supported, so that is why I tried the command above.
```
# from the docs
The current implementation (as of 0.1.0) of the Packager ONLY supports CUDA and Pytorch images from nvcr.io as base images for the MAP. There are efforts in progress to add support for smaller images from dockerhub.
```

Thanks again for the help!
