### ISSUE TITLE
[FEA] Attach meta data to the image object which is output by the segmentation operator

### ISSUE THREAD

**Issue by ghost** [Project-MONAI/monai-deploy-app-sdk#174]
**Is your feature request related to a problem? Please describe.**

The image object which is output by the segmentation operator has no metadata. It's not possible to query the pixel spacing or the orientation of the volume without metadata.

**Describe the solution you'd like**

The image object which is output by the segmentation operator should have the metadata of the input image attached. Values like pixel spacing or orientation.

**Describe alternatives you've considered**

**Additional context**

**Comment by MMelQin** [comment]
The fix is in this [PR](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/186)
