### ISSUE TITLE
[DOC] Add descriptions to projects

### ISSUE THREAD

**Issue by dbericat** [Project-MONAI/monai-deploy-app-sdk#190]
## Report needed documentation

**Report needed documentation**

https://github.com/Project-MONAI/monai-deploy-app-sdk/projects.

**Describe the documentation you'd like**

There are no descriptions for any of the releases. Please add either soul of the release or what's it about with a few words.

**Comment by MMelQin** [comment]
Added overview col. Done.

**Comment by gigony** [comment]
Updated description of each project in https://github.com/Project-MONAI/monai-deploy-app-sdk/projects.
