### ISSUE TITLE
[DOC] Add Overview column to projects using monai-deploy 0.2 as template

### ISSUE THREAD

**Issue by dbericat** [Project-MONAI/monai-deploy-app-sdk#192]
Add Overview column wiht soul, users and release assets for each of the projects. 

Use monai-deploy 0.2 as template:

https://github.com/Project-MONAI/monai-deploy/projects/3

**Comment by MMelQin** [comment]
Added and populated. Done

**Comment by gigony** [comment]
Thanks @MMelQin for doing that! (I was about to do this but you already did! :) )
