### ISSUE TITLE
[DOC] Write documentation for MIS

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/monai-deploy-app-sdk#219]
**New documentation**
We need to write documentation missing for MONAI Inference service.

**Comment by slbryson** [comment]
Assign me as a reviewer and I will review the documentation.

**Comment by vikashg** [comment]
OK

**Comment by vikashg** [comment]
I think @gigony updated the documentation build for 04 and 05.

**Comment by dbericat** [comment]
Once thing is the examples and tutorials, and the other MIS documentation. 

The only documentation we have today for MIS is the README on the github repo. App SDK has a very nice and comprehensive docs on https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/
