### ISSUE TITLE
Output.zip file is corrupted 04_mis_tutorial.ipynb

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/monai-deploy-app-sdk#228]
**Describe the bug**
After running the curl command for monai-inference-service, I get the output.zip file but it is very small and is corrupted
While trying to unzip the output.zip file, I get the following
```
Archive:  output.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of output.zip or
        output.zip.zip, and cannot find output.zip.ZIP, period.
```

**Steps/Code to reproduce bug**
Just running the usual jupyter notebook 

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu 
- Python Version: 3.8 
- Method of MONAI Deploy App SDK install: pip
- SDK Version: 0.2

**Additional context**
It used to run fine and it just appeared today.

**Comment by gigony** [comment]
@vikashg could you please attach the corrupted file here?

/cc @KavinKrishnan

**Comment by vikashg** [comment]
Here is the [file](https://drive.google.com/file/d/1XW8iqDbKmk8msy_ecLtRCwUsMkwIyQIB/view?usp=sharing)

**Comment by MMelQin** [comment]
MIS has served its purpose and is deprecated. It only supported, with http protocol, ingesting a zip of opaque input, and returning an opaque output zip after running a MONAI App Package docker; it never had the functionalities required for MONAI Deploy, e.g. DICOM protocol support.
Please use the MONAI Deploy Express.
