### ISSUE TITLE
Operator to export DICOM Segmentation Storage Instance

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#24]
**User Story**
As an application developer I would like to use a built-in operator using which I can export the output of segmentation results into a DICOM Segmentation Storage SOP Instance so that development time can be reduced.

**Background**
Integrating machine learning (AI) models into clinical workflows requires interoperability with existing imaging systems Interoperability requires adherence to standards. For medical imaging, one of the major standards is DICOM. The existing DICOM standard has methods for representing many forms of ML model output. However, working with DICOM can be challenging for AI developers

- Many have limited familiarity with DICOM
- The breadth and complexity of the standard may make it seem inaccessible
- There has been a lack of DICOM tools that are interoperable with standard ML tooling

The DICOM Segmentation SOP supports the following features:

- The IOD is encoded as a multi-frame image.
- Each frame represents a 2D plane or a slice of a single segmentation category.
- More than one segmentation category is supported per IOD instance. If more than one segmentation category is defined, each is encoded in a separate set of frames (i.e. multiple segmentation categories are not packed into pixels)
- Segmentations are either binary or fractional. Fractional segmentations may be used to represent probability or occupancy percentages.
- The spatial sampling and the extent do not need to be identical to the referenced images. When a Frame of Reference exists, position and orientation are defined within that patient coordinate system.

**Success Criteria**
Operator provides the following outputs at a minimum:
- A way to provide in-memory segmentation results as input to the operator
- A way to configure the generation of Segmentation Store Instance
- Supports multiple categories of segmented voxels in the same segmentation object instance
- Supports binary categorization for each segmentation category
- Segmentation SOP Instances refer to the original series dataset

**Comment by MMelQin** [comment]
Implemented.
