### ISSUE TITLE
[BUG] DICOM Seg instance from DICOMSegmentationWriterOperator now has multiple seg slices on the same frame. 

### ISSUE THREAD

**Issue by MMelQin** [Project-MONAI/monai-deploy-app-sdk#245]
**Describe the bug**
It was observed that the DICOM Seg instance from DICOMSegmentationWriterOperator now has multiple seg slices on the same frame, i.e. multiple segmentation slices each should be overlaid with the referenced original DICOM instance (image slice) are now jammed onto the same frame, like an array of thumbnails, as seen in the screenshot.

This issure has been reproduced in App SDK main, tag 0.1.1, and 0.2, so the changes within PR #238 are not the cause of the errors. It is further noted that the DICOMSegmentationWriterOperator had been tested working properly in release v0.2, except a known issue with a specific input data set.

The generated DICOM Seg instance has been tried on MicroDICOM and Aliza, with the same display issue.

It is unknown what the root cause is as of now.

![image](https://user-images.githubusercontent.com/38891913/150618445-e7164d97-bc98-496b-a84d-8a748769481b.png)

**Steps/Code to reproduce bug**
Run the example Spleen app
Get the DICOM Seg output
Load the DICOM Seg instance with MicroDICOM or Aliza (both are freeware)

**Expected behavior**
Segment(s), which is single in the Spleen app but multiple in the UNETR app, on a specific slice (referring to a specific DICOM instance/image at a given position), is expected to be on its own frame, so that when both DICOM Seg and original DICOM series is loaded together in the viewer, the segment(s) can be shown overlaid on the original slice/image in the DICOM series.

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu 18.04 LTS
- Python Version: 3.7
- Method of MONAI Deploy App SDK install: source
- SDK Version: main in dev mode

**Additional context**
Puzzling as the DICOM Seg writer was tested working correctly, but now, even earlier tagged versions have the issues, at least in dev env.

**Comment by digernes** [comment]
I have encountered the same problem.

**Comment by MMelQin** [comment]
@digernes thanks for your input. The same code was tested working before with numpy array from loading NIfTI or MHD segmentation image, as well as App SDK in memory image object. I'll definitely need to get to the bottom of it before v0.3 release.
