### ISSUE TITLE
[DOC]  Misspelling in monai.deploy.operators.MonaiSegInferenceOperator Definition

### ISSUE THREAD

**Issue by slbryson** [Project-MONAI/monai-deploy-app-sdk#259]
## Report incorrect documentation

**Location of incorrect documentation**
Provide links and line numbers if applicable.
https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/modules/_autosummary/monai.deploy.operators.MonaiSegInferenceOperator.html
latest-v0.2.1

**Describe the problems or issues found in the documentation**

Misspelled word "Oject" ==> "Object" in the API documentation for the operator:
monai.deploy.operators.MonaiSegInferenceOperator¶
Also
Prdicts results using the models(s) with input tensors. ==>Predicts results using the models(s) with input tensors.

**Steps taken to verify documentation is incorrect**

Spell checker

**Suggested fix for documentation**

"Oject" ==> "Object".

**Comment by gigony** [comment]
@slbryson Could you please elaborate on this to decide whether we can include this in v0.3 or not?

**Comment by slbryson** [comment]
This is a very minor set of spelling errors.  It is not high priority (I probably should have just fixed it and submitted a pull request).
It can be done in any release.  I moved it to the Backlog to let the team decide when you would do some of these minor edits.

**Comment by dbericat** [comment]
Make the edits and commit! :)

**Comment by MMelQin** [comment]
@slbryson Thanks for actually pointing the typos in the doc, but on submitting the issues, the comment block tags were not removed, hence the UI did not show your words. I updated the initial submission, by removing the comment tags, to show the actual contents.
