### ISSUE TITLE
Create a data loader pipeline for Nifti or Nrrd images[FEA] 

### ISSUE THREAD

**Issue by vikashg** [Project-MONAI/monai-deploy-app-sdk#270]
**Is your feature request related to a problem? Please describe.**
Similar to the data loader operators here 
https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/monai/deploy/operators/dicom_data_loader_operator.py
Create a nifti loader. 

**Describe the solution you'd like**
Use the Monai Core LoadImage functionality to create the pipeline 

**Describe alternatives you've considered**

**Additional context**
For research Institutes and Labs (other than hospitals)

**Comment by dbericat** [comment]
Closed per https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/361
