### ISSUE TITLE
[BUG] Codes used to describe segments in DICOM SEG writer should be improved

### ISSUE THREAD

**Issue by fedorov** [Project-MONAI/monai-deploy-app-sdk#279]
**Describe the bug**
Codes used to describe segments in DICOM SEG writer should be improved.

**Steps/Code to reproduce bug**
See https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/294fb6e185921a621ad28754d5b97999485e803e/monai/deploy/operators/dicom_seg_writer_operator.py#L440-L463.

**Expected behavior**
1. `SegmentationCategoryType` should refer to the code corresponding to the specific organ. Currently, there is a general code for "Organ", with the specifics about which organ is segmented listed in the `SegmentLabel`. This is not the intended use of this object.
2. Codes should be using SNOMED-CT `SCT` codes, currently used `SRT` codes have been deprecated in DICOM. 

**Environment details (please complete the following information)**

- SDK Version: current as of submitting

**Additional context**
* Relevant commit in dcmqi: https://github.com/QIICR/dcmqi/commit/0cf28290be3ab15afc818b3d1d032f70a8c782a0
* why don't you just use highdicom to write DICOM SEG? https://github.com/herrmannlab/highdicom

**Comment by fedorov** [comment]
I am sure @dclunie will at least be interested to be aware of this discussion.

**Comment by dclunie** [comment]
I assume you mean SegmentedPropertyTypeCodeSequence, not SegmentationCategoryType.

See also [https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7151.html](https://dicom.nema.org/medical/dicom/current/output/chtml/part16/sect_CID_7151.html)

**Comment by dbericat** [comment]
Thanks for the feedback! @MMelQin, @vikashg and/or @gigony will address the first part. 

Regarding highdicom, we all want to do that. It's just that @CPBridge has been busy lately, right Chris? ;)

Check this out: https://github.com/Project-MONAI/monai-deploy-app-sdk/issues/195

It is currently planned for 0.4.0. https://github.com/Project-MONAI/monai-deploy-app-sdk/projects/6

**Comment by hackermd** [comment]
@dbericat thanks for your feedback and sorry for the delay on our end. @CPBridge and I will finalize the PR as soon as possible.

**Comment by fedorov** [comment]
If the plan is to switch to highdicom, this issue will not be applicable - feel free to close.

**Comment by MMelQin** [comment]
Thanks for feedbacks. Agree the existing DICOM Seg Writer code needs to be enhanced, for its intended purpose, and also there is a defect I filed and need to fix.
