### ISSUE TITLE
[FEA] Test compatibility with MONAI core latest, 0.8.1, and enable using this version in App SDK 

### ISSUE THREAD

**Issue by MMelQin** [Project-MONAI/monai-deploy-app-sdk#287]
**Is your feature request related to a problem? Please describe.**
Existing releases of App SDK depends on MONAI 0.6.0, though newer releases of MONAI have been published on pypi.org. For the specific use of MONAI in the App SDK, mostly transforms and Compose in the seg inference operator, there is unlikely any issues when using the latest MONAI release, though testing is required and the Python requirement need to change (instead of pinging to a specific version, may consider minimal version being 0.6.0)

**Describe the solution you'd like**
Install latest MONAI Pypi package, change requirement in the module depending on MONAI, and test example apps.

**Describe alternatives you've considered**
N/A

**Additional context**
Users of MONAI may have already started using the latest MONAI, and would like to know App SDK is compatible with it.

**Comment by vikashg** [comment]
I think we should build a different application package other than spleen segmentation. That ways we will have a new and different app. 
Working on it.

**Comment by dbericat** [comment]
Agreed. That is why I wanted to bring that topic yesterday. We can create a github discussion to brainstorm all together.

**Comment by MMelQin** [comment]
It is a great idea @vikashg.
For example applications that depend on MONAI core, we have Spleen, Liver and Tumor, and UNETR, all segmentation models. It will be great to have additional ones, and for the next release, we'll be introducing applications supporting multiple models.

This issue will focus on ensuring MONAI 0.8.1 is compatible with existing modules.

**Comment by MMelQin** [comment]
@vikashg @dbericat @ericspod The pull request was approved by @gigony and merged. We are good to go with the latest MONAI core, v0.8.1, which is as expected.

Existing App SDK libs and applications depend on MONAI core functionalities that support backwards compatibility, and also forward compatibility/no breaking changes, so we use "monai>=0.8.1", until otherwise.
