### ISSUE TITLE
IndexError: Caught IndexError in DataLoader worker process 0. 

### ISSUE THREAD

**Issue by CS-Rorita** [Project-MONAI/monai-deploy-app-sdk#297]
I tried to run a 3D classification template which uses MRI data from IXI https://colab.research.google.com/github/Project-MONAI/tutorials/blob/master/3d_classification/torch/densenet_training_array.ipynb
When I just change the data for my private data 
```
`# IXI dataset as a demo, downloadable from https://brain-development.org/ixi-dataset/
images = [
    "/content/asd (1).nii.gz","/content/asd (2).nii.gz","/content/asd (3).nii.gz","/content/asd (4).nii.gz","/content/asd (5).nii.gz",
    "/content/asd (6).nii.gz","/content/asd (7).gz","/content/asd (8).gz","/content/asd (9).gz","/content/healthy (1).nii.gz",
    "/content/healthy (2).nii.gz","/content/healthy (3).nii.gz","/content/healthy (4).nii.gz","/content/healthy (5).nii.gz","/content/healthy (6).nii.gz",
    "/content/healthy (7).nii.gz","/content/healthy (8).nii.gz","/content/healthy (9).nii.gz","/content/healthy (10).nii.gz","/content/healthy (11).nii.gz"
]

# 2 binary labels for gender classification: man or woman
labels = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Represent labels in one-hot format for binary classifier training,
# BCEWithLogitsLoss requires target to have same shape as input
labels = torch.nn.functional.one_hot(torch.as_tensor(labels)).float()`
```
I get an IndexError: Caught IndexError in DataLoader worker process 0.
  No other part of the code has been changed so I don't know what caused the error

I searched and found that the length of the data set should match the epochs and I did that and the error still exists

Then again I only left 20 images (the same number of images that were with the original code) and the problem also exists

Is there anyone who can tell me why my data won't work with the code? What did I do wrong that I didn't notice?

Thanks in advance

**Comment by vikashg** [comment]
Hi @CS-Rorita The reason you are getting this error is because you are encoding the binary labels as 0 and 1. You should encode the labels as 
for 0 it should be [1, 0] and for 1 it should be [0, 1]. If you make those changes it should work. so for a batch your label array should look like [[0, 1], [0, 1], [1, 0]]. You can also post this query in monai-core discussions.

**Comment by CS-Rorita** [comment]
Thanx .. I tried that . It works well in the part of reading the dataset . However it arise an error as `RuntimeError: 0D or 1D target tensor expected, multi-target not supported` when compile the model 

![image](https://user-images.githubusercontent.com/67325575/167980793-a1557a9c-ed48-4cb4-9bdd-5f087c46659b.png)

```
 for batch_data in train_loader:
        step += 1
        inputs, labels = batch_data[0].to(device), batch_data[1].to(device)
        optimizer.zero_grad()
        outputs = model(inputs)
        loss = loss_function(outputs, labels)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
        epoch_len = len(train_ds) // train_loader.batch_size
        print(f"{step}/{epoch_len}, train_loss: {loss.item():.4f}")
        writer.add_scalar("train_loss", loss.item(), epoch_len * epoch + step)
```

**Comment by MMelQin** [comment]
Closing this issue as answer has been provided and the issue was not related to App SDK.
