### ISSUE TITLE
[DOC] Missing python dependencies for the segmentation app

### ISSUE THREAD

**Issue by jeanpatrickleger** [Project-MONAI/monai-deploy-app-sdk#299]
## Report incorrect documentation

**Location of incorrect documentation**

https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/03_segmentation_app.html

**Describe the problems or issues found in the documentation**

Missing python dependencies for the segmentation app to run properly : 
**Steps taken to verify documentation is incorrect**

The tutorial steps work after manually adding trimesh and numpy-stl libs ( pip install  numpy-stl trimesh  )

**Suggested fix for documentation**

update the code block title "Executing from Shell" , replace the line : 

 pip install monai pydicom SimpleITK Pillow nibabel

by :

pip install monai pydicom SimpleITK Pillow nibabel numpy-stl trimesh

---

## Report needed documentation

**Report needed documentation**

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**

**Comment by MMelQin** [comment]
@jeanpatrickleger Thanks for reporting this issue. Apologies that the doc was out of sync.

**Comment by MMelQin** [comment]
Added a comment in the [latest doc](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/03_segmentation_app.html) on these dependencies when an app uses the STL Conversion operator.
