### ISSUE TITLE
[DOC] 

### ISSUE THREAD

**Issue by paynowski** [Project-MONAI/monai-deploy-app-sdk#305]
## Report incorrect documentation

**Location of incorrect documentation**
(https://docs.monai.io/projects/monai-deploy-app-sdk/en/stable/getting_started/tutorials/03_segmentation_app.html)

**Describe the problems or issues found in the documentation**
Missing several install steps.

**Steps taken to verify documentation is incorrect**
I had to add the following pip installations: scikit-image, numpy-stl and trimesh

**Suggested fix for documentation**
Add missing installation steps

## Report needed documentation

**Report needed documentation**

**Describe the documentation you'd like**
Add the extra pip steps in the "Execute from Shell" section

**Steps taken to search for needed documentation**

**Comment by MMelQin** [comment]
Added a comment in the [latest doc](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/03_segmentation_app.html) on these dependencies when an app uses the STL Conversion operator.
