### ISSUE TITLE
[BUG] Variable not properly set after loading model instance

### ISSUE THREAD

**Issue by aihsani** [Project-MONAI/monai-deploy-app-sdk#326]
**Describe the bug**
It seems `self._init_completed` is not set after successfully loading a model
https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/monai/deploy/operators/monai_bundle_inference_operator.py#L463

**Steps/Code to reproduce bug**
Use `ai_spleen_seg_app`

**Expected behavior**
`self._init_completed` is set to `True`

**Environment details (please complete the following information)**

- OS/Platform: Ubuntu
- Python Version: 3.8.10
- Method of MONAI Deploy App SDK install: pip
- SDK Version: 0.4.0

**Comment by ericspod** [comment]
It looks like lines 458-463 should be:

```python
                with self._lock:
                    if not self._init_completed:
                        self._bundle_path = self._model_network.path
                        self._init_config(self._bundle_config_names.config_names)
                        self._init_completed = True
```

There is an extra but harmless conditional check currently.

**Comment by MMelQin** [comment]
> It looks like lines 458-463 should be:
> 
> ```python
>                 with self._lock:
>                     if not self._init_completed:
>                         self._bundle_path = self._model_network.path
>                         self._init_config(self._bundle_config_names.config_names)
>                         self._init_completed = True
> ```
> 
> There is an extra but harmless conditional check currently.

Thanks. It is not an issue at runtime, and I thought the style/format checkers should at least give a warning. Anyway, I will add the R- Value there in the code.
