### ISSUE TITLE
[BUG] Fix Documentation link on App SDK Pypi page

### ISSUE THREAD

**Issue by dbericat** [Project-MONAI/monai-deploy-app-sdk#338]
**Describe the bug**
Documentation link on [Pypi App SDK page](https://pypi.org/project/monai-deploy-app-sdk/) mistakenly lead to MONAI Core docs instead of App SDK one

**Steps/Code to reproduce bug**
[Pypi App SDK page](https://pypi.org/project/monai-deploy-app-sdk/) -> Project Links menu on the left -> Documentation - leads you to https://docs.monai.io/en/stable/ 

**Expected behavior**
It should link to https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/

**Comment by MMelQin** [comment]
@dbericat Please see the[ setup.cfg file in PR](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/373/files#diff-fa602a8a75dc9dcc92261bac5f533c2a85e34fcceaff63b3a3a81d9acde2fc52)
