### ISSUE TITLE
[DOC] IHE Consistent Time

### ISSUE THREAD

**Issue by IntegratorBrad** [Project-MONAI/monai-deploy-app-sdk#344]
There should be a note for support of IHE Consistent Time. 

E.g. "MONAI is an SDK that enables AI developers to construct processing pipelines that take inputs (like DICOM) and construct outputs. MONAI relies upon the operating system time on its OS (e.g. Ubuntu using NTP) and uses that for any specific activities (like event and SOLE reporting). For creation of DICOM or HL7 objects that use time, it would be incumbent on the developer to appropriately use the available system time service and reflect the correct time in those objects properly. "

Add a section on Standards, maybe in the introduction:
https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/introduction/index.html

Add links to DICOM objects and guidance, and HL7 if relevant.

Add IHE, and reference relevant profiles. 

IHE Consistent Time should show up, using that paragraph above as a note describing consistent time support.

## Report incorrect documentation

**Location of incorrect documentation**

**Describe the problems or issues found in the documentation**

**Steps taken to verify documentation is incorrect**

**Suggested fix for documentation**

---

## Report needed documentation

**Report needed documentation**

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**

**Comment by MMelQin** [comment]
As for App SDK, there is no restriction on where and how the MONAI Application Package will be hosted, though the first known target hosting platform is MONAI Deploy. The built-in operator and application classes make no assumptions on time zone the application will be hosted, in what time zone the original DICOM instances were created, and in what time zone the DICOM device is in or expect the generated DICOM object will have. So, the built-in class will only use the time provided by the underlying OS in local time for the zone that the OS is configured.

DICOM Standards define the TimezoneOffsetFromUTC tag (0008, 0201), for use along with Content Time, but being a Type 3 attribute, it is not typically set.
 
Important to note, with Cloud hosting the MAPs, sending devices, e.g. PACS and other DICOM Devices, can be in a time zone different from the platform hosting the MAPs, and the sent DICOM inputs may also have `time` attributes set with the acquisition devices' local time, which may very well be different from the PACS's own time zone. With such inherent issues around recorded time, and no consistent setting or consuming of UTC offset in DICOM objects or PACS, there is no way for the MAP to determine what specific time zone to use for setting the `local` time, it will at best try to set the `Time Zone Offset From UTC`, in the generated DICOM object, but not guaranteed to be present per DICOM Standards.

**Comment by MMelQin** [comment]
@IntegratorBrad please see the related [PR ](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/373)for the wording on consistent time.

I have also added the mention of Timezone Offset From UTC in the generated DICOM instance, which to me is more important for a system with equipment and contributing equipment across multiple time zones. It is something that would and has caused some serious issues in the real world.

**Comment by MMelQin** [comment]
This is another piece of info confirming that TimeZoneOffsetFromUTC is important. When the AI performer is run in a docker container, the date and time retrieved from the OS is based on UTC+0, not the host's local time zone.

```
(.venv) mqin@mingq-dt:~/src/monai-deploy-app-sdk$ dcmdump output/1.2.826.0.1.3680043.10.511.3.10423037268986458986908814334102350.dcm | grep Time
(0008,0030) TM [162720]                                 #   6, 1 StudyTime
(0008,0031) TM [232615]                                 #   6, 1 SeriesTime
(0008,0033) TM [232610.375877]                          #  14, 1 ContentTime
(0008,0201) SH [+0000]                                  #   6, 1 TimezoneOffsetFromUTC
(0010,0032) TM [010100.000000]                          #  14, 1 PatientBirthTime
```
