### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#35]
- Setup pre-commit script
- Setup test case coverage
  - https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/164
- Setup workflow

**Comment by evberrypi** [comment]
I have [137](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/137) created to add in basic test coverage (formatting + unit testing). 
Leaving this issue open because we are missing

- [ ] Stage to package into .whl & tar.gz file
- [ ] Release Pipeline
- [ ] Weekly Release to Pypi

**Comment by evberrypi** [comment]
Closing as this task "initial setup" is completed,
Task to track building the release pipeline is in #261
