### ISSUE TITLE
Fix the naming convention for Image [DOC] 

### ISSUE THREAD

**Issue by josegcpa** [Project-MONAI/monai-deploy-app-sdk#356]
Not really documentation, but the Image domain is actually referring to, as far as I can tell, an Array, not specifically an Image. I was about to submit a feature request for a Vector or Array Domain but the Image Domain is capable of handling most shapes. If changing the name of the Domain is too cumbersome (which is understandable) more details should be included in the documentation (i.e. https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/modules/_autosummary/monai.deploy.core.domain.Image.html)

**Steps taken to verify documentation is incorrect**
I looked at the code corresponding to the Image Domain to verify it was not specific for 2D or 3D images.

**Suggested fix for documentation**
I have three alternatives by cumbersomeness:
1) Update documentation
2) Introduce an alias for the Image class called Array
3) Introduce a new parent class for Image called Array (if the developers are hoping to further develop the Image Domain with specific capabilities)

**Comment by MMelQin** [comment]
@josegcpa Please see the doc update in [this file of the pending PR](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/373/files#diff-4a990fa290717ce6e9867e66cfbea5b7788072ca560829874ff1e63fd647fb32)

**Comment by josegcpa** [comment]
> @josegcpa Please see the doc update in [this file of the pending PR](https://github.com/Project-MONAI/monai-deploy-app-sdk/pull/373/files#diff-4a990fa290717ce6e9867e66cfbea5b7788072ca560829874ff1e63fd647fb32)

This is really great, pretty much solves it for me. I still think that it is not the most intuitive class name but it is a good compromise. Thank you!
