### ISSUE TITLE
[BUG] module import error

### ISSUE THREAD

**Issue by mingxin-zheng** [Project-MONAI/monai-deploy-app-sdk#371]
**Describe the bug**

I got the following error message when trying to import the latest version of monai-deploy-sdk in edit mode:

```bash
File "/opt/conda/lib/python3.8/site-packages/monai/deploy/operators/dicom_encapsulated_pdf_writer_operator.py", line 18, in <module>
    from PyPDF2 import PdfReader
```

Installing the package manually resolves the issue:
```
pip install PyPDF2
```

**Comment by MMelQin** [comment]
Thanks, and good catch. I missed adding this to the requirements file.
