### ISSUE TITLE
Supporting multiple models on the same app [FEA] 

### ISSUE THREAD

**Issue by josegcpa** [Project-MONAI/monai-deploy-app-sdk#393]
**Is your feature request related to a problem? Please describe.**
Basically, in some instances it is useful to have more than one available model - particularly, I wanted to have two different models for different sequence types, but at the moment this requires me exporting both models as a "super model" which splits the input along a dimension and concatenating the input prior to feeding it to the model. 

**Describe the solution you'd like**
I think it would be cleaner if I could specify more than one model and have a way of defining which model operator uses which (by index or similar).

**Describe alternatives you've considered**
The alternatives I have considered are the ones described in the first section.

**Comment by MMelQin** [comment]
@josegcpa thanks for raising the needs for multi-model support.

In fact, multi-model multi-AI support is one of the key requirements of the App SDK, and has been supported from v0.1, just that this feature has not been well publicized.

Please see this [example app](https://github.com/Project-MONAI/monai-deploy-app-sdk/tree/main/examples/apps/ai_multi_ai_app), which I believe is what you want. Please confirm, and you are also welcome to contribute a more meaningful multi-model example!

**Comment by josegcpa** [comment]
> Please see this [example app](https://github.com/Project-MONAI/monai-deploy-app-sdk/tree/main/examples/apps/ai_multi_ai_app), which I believe is what you want. Please confirm, and you are also welcome to contribute a more meaningful multi-model example!

Exactly what I wanted :-) it would be really good to see some clearer guidelines for this; but this example is already great help, thank you! I am working with multiparametric MRI and with different tasks so it would be wonderful to see more examples of multi-modality + multi-model MONAI-deploy apps.
