### ISSUE TITLE
[IMP] Breast Density Classification app to make output DICOM SR instance part of the original study

### ISSUE THREAD

**Issue by MMelQin** [Project-MONAI/monai-deploy-app-sdk#395]
**Is your enhancemnet request related to a problem? Please describe.**
The Breast Density Classification example app generates DICOM SR instance as if in a new study. This by itself is supported if the original input DICOM is not available, e.g. in cases where input images are non-DICOM files.

The example as created expects to load and parse input DICOM files, so it's expected that the generated DICOM SR instance will copy the study level tags of the input, in order to be of the same study.

**Describe the solution you'd like**
The generated DICOM SR instance will at least re-use the Study Instance UID.
The App SDK Text SR writer actually already support the "copy_tags" features, so long as the optional is used and the original DICOM Series object is passed into.

**Describe alternatives you've considered**
No need as the functionality is already supported by App SDK

**Additional context**
Not copying the study level tags of the input DICOM to the generated DICOM SR instance will not allow the SR be associated with the original study.

**Comment by vikashg** [comment]
I think the pull request takes care of it right. So we can close it.

**Comment by MMelQin** [comment]
> 

Yes, the PR for addressing this improvement has been merged so this one is done.
