### ISSUE TITLE
[BUG] Problem with dicom_seg_writer_operator

### ISSUE THREAD

**Issue by hossam99-9** [Project-MONAI/monai-deploy-app-sdk#397]
While trying to use MONAI deploy , while viewing segmentation overlaied over the original scan on OHIF , there was a shift between the segmentation and image . 

In 3d slicer I had the same problem but using extension solved the problem. 

The seg file has tags that solve the problem but it's not being parsed in OHIF.

the original scan was 204 instance but the segmentation was only 87.

probably the problem is in the ( dicom_seg_writer_operator ) module , the flag (skip empty frames) in highdicom  is set to TRUE by default ,

making it optional will fix the issue.

Model used for segmentation ( spleen_ct model ( Model zoo ) )

Thanks in advance.

**Comment by MMelQin** [comment]
@hossam99-9 Thanks for the report and the workaround. @CPBridge 

As you rightfully mentioned, it is the DICOM Seg viewer(s) which is limited and not fully compliant with DICOM standards. The output from DICOM Seg Writer, using highdicom backend, is validated by DICOM validation tools, e.g. David Clunie's [validator](https://www.dclunie.com/dicom3tools/dciodvfy.html), and in fact, David is a contributor to highdicom.

For OHIF, there seem be more than this issue, e.g. segments displayed out of position, and an [open issue](https://github.com/OHIF/Viewers/issues/2833) is on its board. as well as this [one ](https://github.com/Project-MONAI/monai-deploy/issues/96) on MONAI Deploy board. 

So, this is not a bug in highdicom or the App SDK Seg Writer. However, we can consider adding the option to alter the `omit_empty_frames` =True` to workaround the issue, and make this as an improvement.
