### ISSUE TITLE
replace the URL to the "Simple Image Processing App"

### ISSUE THREAD

**Issue by Abdelkrim** [Project-MONAI/monai-deploy-app-sdk#430]
**Describe the bug**

The URL to the "Simple Image Processing App" displayed in the installation page is incorrect
An update is required

**To Reproduce**
1. Go to [https://monai.io/started.html#installation](https://monai.io/started.html#installation)
2. Move down to the "**MONAI Deploy Tutorials**" section
3. Click on the link **Simple Image Processing App** : 
4. https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/getting_started/tutorials/01_simple_app.html

**Expected behavior**

This URL is loaded instead : [https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/index.html](https://docs.monai.io/projects/monai-deploy-app-sdk/en/latest/index.html)

**Screenshots**

Error if I click on the link 

![image](https://github.com/Project-MONAI/MONAI/assets/791663/e468020e-3dd0-4e73-a2d0-8374bea78a63)

**Environment**

regular browser : Firefox

**Additional context**

N/A

**Comment by MMelQin** [comment]
Thank you @Abdelkrim for raising the issue.

The links on monai.io for the Deploy App SDK had changed, with the URL fragment `latest` to `stable`. Will plan to address this error.

**Comment by zephyrie** [comment]
Thanks, @Abdelkrim.  This issue should now be fixed.  Along with the update for the links, we've removed some no longer relevant information. 

@MMelQin, can you verify everything looks good?

**Comment by MMelQin** [comment]
Thanks, @zephyrie, all links are working now.

**Comment by MMelQin** [comment]
Closing this one as the links have been updated
