### ISSUE TITLE
[IMP] Switch from versioneer-518 to versioneer?

### ISSUE THREAD

**Issue by tjni** [Project-MONAI/monai-deploy-app-sdk#450]
**Is your enhancement request related to a problem? Please describe.**

According to https://github.com/python-versioneer/versioneer-518/issues/5, it might be the case that versioneer can do everything that versioneer-518 can do. Without looking into it deeply, it has a "Build-time dependency mode" that is also not vendored. 

I am working on packaging and use [`build`](https://pypa-build.readthedocs.io/en/stable/) to build this package. By default, it will validate that all declared build dependencies are present, and I'm hoping to skip packaging versioneer-518 if it is obsolete.

**Describe the solution you'd like**

I'm not too familiar with versioneer and how this project uses it, but do you think it would be possible to switch over?

**Comment by MMelQin** [comment]
versioneer, in combination with bunmpversion, helps us bump/set release version, as well as setting up the sdk as editable package during dev. On release a specific version of the SDK package, a static _version.py file is generated and used for the actual build. Maybe you are building with the _verdion.py file in the repo, hence the versioneer dependency is detected?

**Comment by MMelQin** [comment]
During bumping version for release. the SDK version is stored is in fact stored in [bumpversion cfg file](https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/.bumpversion.cfg)
