### ISSUE TITLE
Error with monai.transforms  AddChannel 

### ISSUE THREAD

**Issue by ajikmr** [Project-MONAI/monai-deploy-app-sdk#470]
Hello.
I am trying to run following tutorial notebook on colab. I also tried it on local vm.

https://github.com/Project-MONAI/monai-deploy-app-sdk/blob/main/notebooks/tutorials/02_mednist_app.ipynb

AddChannel call gives error.
ImportError: cannot import name 'AddChannel' from 'monai.transforms'

I am able to run by replacing it with EnsureChannelFirst for the import
        #AddChannel,
        EnsureChannelFirst,

And similarly replacing AddChanne()  calls  with EnsureChannelFirst(). 

Same works for both colab run or local vm run. Is this corrrect? It will be great to have tutorial notebooks / examples updated.

Regards.

Local vm details
- OS/Platform: Ubuntu 22.04 LTS
- Python Version: 3.11.0
- Method of MONAI Deploy App SDK install: pip
- SDK Version: 0.6.0 (latest)

**Comment by MMelQin** [comment]
@ajikmr Thank you so much for reporting the issue, as well as the debugging results.

As you must have noticed, the dependency package, monai, had the new v1.3.0 released on Oct 12th, 2023, while the Jupyter Notebook did not pip the monai version at all, at the peril of deprecated functions in the dependencies.

The examples and tutorials are not part of the monai-deploy-app-sdk package, and can be updated in the repo when issues are found and fixed. so,

**Do you prefer submitting a pull request to fix the Jupyter Notebook**, or leave it to me?

**Comment by MMelQin** [comment]
> Hello @MMelQin ,
> 
> Thanks a lot for your prompt response. I am new to Monai framework, and so would not be able to submit pull request. It will be great if you could do it.

Thanks. Will do ASAP.
