### ISSUE TITLE
Load metadata error : Error to do request(bug)

### ISSUE THREAD

**Issue by priya21sini** [Project-MONAI/monai-deploy-app-sdk#477]
**Please use MONAI Deploy App SDK's Discussions tab**

For questions relating to MONAI Deploy App SDK usage, please do not create an issue.

Instead, use [MONAI Deploy App SDK's GitHub Discussions tab](https://github.com/Project-MONAI/monai-deploy-app-sdk/discussions). This can be found next to Issues and Pull Requests along the top of our repository.

I can't be able to package the app. Its showing error while loading metadata for the base image. I am working on mednist- classifier-app(prebuilt model).

**Comment by MMelQin** [comment]
Please try the newly release App SDK v1.0, and we'll follow up in the discussions as needed.
