### ISSUE TITLE
[bug] monai.deploy module not found

### ISSUE THREAD

**Issue by nitin271080** [Project-MONAI/monai-deploy-app-sdk#478]
when using monai-deploy-app-sdk==0.5.0 python 3.8 minicoda 
giving error on execution on 

python examples/apps/ai_spleen_seg_app/app.py

Traceback (most recent call last):
  File "examples/apps/ai_spleen_seg_app/app.py", line 18, in <module>
    from monai.deploy.conditions import CountCondition
ModuleNotFoundError: No module named 'monai.deploy'

**Comment by MMelQin** [comment]
Thanks for reporting the error @nitin271080.

Wonder if in the virtual env monai-deploy-app-sdk==0.5.0 is used while the examples applications are from the latest/main in the repo. The examples in the main branch are dependent on monai-deploy-app-sdk v0.6.0 and would not work with v0.5.0 of the SDK.

**Comment by MMelQin** [comment]
Follow up in discussions as needed.
