### ISSUE TITLE
Operator to perform classification inference using a Torchscript based model

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#6]
**User Story**
As an application developer I would like to use a built-in operator using which I can perform classification type inference with a TorchScript based model so that development time to write code for performance can be minimized

**Background**
TorchScript provdes an intermediate representation of a PyTorch model (subclass of nn.Module) that can then be run in a high-performance environment. There should be an easy-to-use mechanism using which app developers can make using of such models in MONAI Deploy

**Success Criteria**
Operator Provides the following outputs at a minimum:
- A way to load the model
- A way to provide input data (tensors) to perform classification type inference
- A way to perform classification inference using the model
- A way for the app developer to override & augment pre-transform step necessary before performing inference
- A way for the app developer to override & augment post-transform step necessary before performing inference
- A way to specify how much data should be used at a time from a sample (sliding window vs all pixels of a sample) during inference

**Comment by gigony** [comment]
Done as part of v0.1.0
Closing.
