### ISSUE TITLE
Operator to export classification results as DICOM SR SOP Instance

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#7]
**User Story**
As an application developer I would like to use a built-in operator using which I can write the output of a classification results into a DICOM Structured Report SOP Instance so that development time can be reduced.

**Background**
Integrating machine learning (AI) models into clinical workflows requires interoperability with existing imaging systems Interoperability requires adherence to standards. For medical imaging, one of the major standards is DICOM. The existing DICOM standard has methods for representing many forms of ML model output. However, working with DICOM can be challenging for AI developers 
- Many have limited familiarity with DICOM 
- The breadth and complexity of the standard may make it seem inaccessible
- There has been a lack of DICOM tools that are interoperable with standard ML tooling

**Success Criteria**
- A way to provide in-memory classification results as input to the operator
- A way to configure the generation of SR Object instance
- API Documentation for the Operator
- Unit Test Case(s)

**Comment by gigony** [comment]
Done as part of v0.2.0
Closing.
