### ISSUE TITLE
Creating a MONAI Application Package

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#8]
**User Story**
As an application developer I would like to convert the Python application based on the MONAI Deploy App Framework into a MONAI Application Package so that I can execute my application in any conforming environment

**Background**
The MONAI Application Package specification provides a mechanism to package MONAI Deploy applications so that they can be served out by an Application Server in a production-like environment or an Application Runner in the local development workstation.

**Success Criteria**
Honors the resource needs for application
Conforms to MONAI App Package Specification

**Comment by gigony** [comment]
Done as part of v0.1
Closing this.
