### ISSUE TITLE
Operator for 2D/3D image visualization

### ISSUE THREAD

**Issue by rahul-imaging** [Project-MONAI/monai-deploy-app-sdk#9]
**User Story**
As an application developer I would like to visualize the input medical images that are fed to an Operator and the output medical images that are generated by the Operator so that I can debug the Operator in my local workstation

**Background**
Typical AI inference and/or transformation type operators ingest and generate imaging data that are not easy to visualize using off-the-shelf viewers. Key to debugging the functionality of an operator is to visualize the input and output datasets and analyze them. However most open-source image visualization systems are not suitable for use during AI algorithm development

- No medical imaging visualization toolkit offers a mechanism so that visualization can be easily integrated programmatically during app development. 
- Most open-source viewers offer visualizing 2D slices, but not 3D 
- Those which can render 3D datasets often cannot handle large 3D datasets and also do not offer all relevant modes of visualization. 

**Success Criteria**
Operator provides the following outputs at a minimum:

- Ability to render CT, MR, X-Ray Datasets
- Visualization Modes: Original Slice, DVR, MaxP, MinP
- Allows modification of transfer function for DVR views
- Basic Interaction: Zoom, Rotate  (3D only), Pan
- Navigation of slices in original slice mode
- Operator linkable with other compatible operators in an application

**Comment by AndreasHeumann** [comment]
I think we can close this, the operator is implemented.
